Repository teller-protocol/CeFi-Frontend, pull requests merged in 2020-08, with the labels that each got.

#36 Travis setup
  .travis.yml
Labels: devops, enhancement

#34 [Teller-48] Integrating API call for arrowheadCRA
  api/plaid.js
  package-lock.json
  src/actions/ConnectPlaid.tsx
  src/actions/RegisterLoan.ts
  src/components/Borrow/Borrow.tsx
  src/components/Borrow/FirstStageTable.tsx
  src/components/BorrowDetailsModal/index.scss
  src/components/BorrowDetailsModal/index.tsx
  src/components/BorrowingAccountLink/index.scss
  src/components/BorrowingAccountLink/index.tsx
  src/components/BorrowingSection/index.scss
  src/components/BorrowingSection/index.tsx
  src/components/LoanCreateCard/index.scss
  src/components/LoanCreateCard/index.tsx
  src/components/Plaid/index.tsx
  src/components/UI/CustomSubmitButton.tsx
  src/components/ZeroRouting.tsx
  src/models/ArrowheadCRA.ts
  src/models/DataProviders.tsx
  src/models/Plaid/index.tsx
  src/util/constants.tsx
  src/views/Home/index.scss
  src/views/Home/index.tsx
Labels: enhancement

#40 Bump Staging
  .travis.yml
  api/plaid.js
  package-lock.json
  src/actions/ConnectPlaid.tsx
  src/actions/RegisterLoan.ts
  src/components/Borrow/Borrow.tsx
  src/components/Borrow/BorrowMetrics.tsx
  src/components/Borrow/FirstStageTable.tsx
  src/components/Borrow/SecondStageTable.tsx
  src/components/Borrow/ThirdStageTable.tsx
  src/components/Borrow/borrow.scss
  src/components/BorrowDetailsModal/index.scss
  src/components/BorrowDetailsModal/index.tsx
  src/components/BorrowingAccountLink/index.scss
  src/components/BorrowingAccountLink/index.tsx
  src/components/BorrowingSection/index.scss
  src/components/BorrowingSection/index.tsx
  src/components/Lend/CurrencyDropdown.tsx
  src/components/Lend/Lend.tsx
  src/components/Lend/SubmitApproveButton.tsx
  src/components/Lend/lend.scss
  src/components/LoanCreateCard/index.scss
  src/components/LoanCreateCard/index.tsx
  src/components/LoginButton/LoginButton.tsx
  src/components/LoginModals/LoginModals.tsx
  src/components/LoginWeb3/index.tsx
  src/components/Plaid/index.tsx
  src/components/Routing.tsx
  src/components/SuccessScreen/SuccessScreen.tsx
  src/components/UI/Card.tsx
  src/components/UI/CustomDropdown.tsx
  src/components/UI/CustomSubmenuLink.tsx
  src/components/UI/CustomSubmitButton.tsx
  src/components/UI/LoadingAnimation.tsx
  src/components/UI/SubmenuCard.tsx
  src/components/UI/card.scss
  src/components/View/index.scss
  src/components/View/index.tsx
  src/components/ZeroRouting.tsx
  src/context/app.tsx
  src/hooks/AppContext.tsx
  src/models/ArrowheadCRA.ts
  src/models/DataProviders.tsx
  src/models/Plaid/index.tsx
  src/util/constants.tsx
  src/views/Home/index.scss
  src/views/Home/index.tsx
Labels: devops

#44 [LOAN-36] Fixing out of bounds number error for Dai spend approval.
  src/models/Contracts.tsx
Labels: bug

#45 [LOAN-36] Adding 100x approval amount during lending process.
  src/components/Lend/SubmitApproveButton.tsx
Labels: bug

#50 Add correct 10x approval when requested.
  src/actions/lendDai.tsx
  src/components/Lend/SubmitApproveButton.tsx
  src/models/Contracts.tsx
Labels: enhancement

#63 Fixing the heroku server error
  index.js
Labels: bug

#52 [LOAN-14] Adding web2 server connection and adding borrow ArrowheadCRA endpoint.
  package-lock.json
  src/components/Borrow/Borrow.tsx
  src/components/Borrow/LoanSizeSelection.tsx
  src/context/app.tsx
  src/context/borrowContext.tsx
  src/models/ArrowheadCRA.ts
  src/models/Contracts.tsx
  src/models/DataProviders.tsx
  webpack.development.config.js
Labels: enhancement

#65 Bump staging
  index.js
  package-lock.json
  package.json
  src/actions/signInContracts.tsx
  src/components/AssetChangeWarningModal/AssetChangeWarningModal.tsx
  src/components/Borrow/Borrow.tsx
  src/components/Borrow/LoanSizeSelection.tsx
  src/components/Lend/Lend.tsx
  src/components/Lend/LendAmountInput.tsx
  src/components/Lend/LendMetrics.tsx
  src/components/LoginButton/LoginButton.tsx
  src/components/Navigation/Navigation.tsx
  src/components/ProcessingScreen/ProcessingScreen.tsx
  src/components/SuccessScreen/SuccessScreen.tsx
  src/context/app.tsx
  src/context/borrowContext.tsx
  src/context/lendContext.tsx
  src/hooks/AppContext.tsx
  src/models/ArrowheadCRA.ts
  src/models/Contracts.tsx
  src/models/DataProviders.tsx
  src/models/FetchTokenData.tsx
  src/util/constants.tsx
  webpack.development.config.js
Labels: devops

#69 Fix ssl redirects
  index.js
Labels: bug

#74 Adding fixes for development environment.
  .travis.yml
  webpack.config.js
Labels: bug

#80 Adding contract withdrawal to ATM.
  src/actions/DashboardLendActions.tsx
  src/actions/redeemZDai.tsx
  src/actions/signInContracts.tsx
  src/components/Dashboard/LendWithdrawSubsection.tsx
  src/components/LendingSection/index.tsx
  src/components/UI/CustomInput.tsx
  src/models/Contracts.tsx
Labels: enhancement
